import { afterEach, describe, expect, it } from 'bun:test';
import { existsSync, lstatSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { applyCapturedEntryHtml, ensureDir, writePlaceholderForMissing } from '@/files.js';

describe('writePlaceholderForMissing', () => {
    const tempDirs: string[] = [];

    afterEach(() => {
        for (const dir of tempDirs.splice(0)) {
            rmSync(dir, { force: true, recursive: true });
        }
    });

    it('should write placeholder scripts for unavailable external javascript assets', async () => {
        const outDir = mkdtempSync(path.join(tmpdir(), 'shibuk-files-'));
        tempDirs.push(outDir);

        const written = await writePlaceholderForMissing(
            'http://localhost:3000/_external/pm.redbull.com/js/script.js',
            outDir,
        );
        expect(written).toBe(true);

        const content = await Bun.file(path.join(outDir, '_external', 'pm.redbull.com', 'js', 'script.js')).text();
        expect(content).toContain('Placeholder generated by shibuk');
    });

    it('should not write placeholder scripts for same-host javascript assets', async () => {
        const outDir = mkdtempSync(path.join(tmpdir(), 'shibuk-files-'));
        tempDirs.push(outDir);

        const written = await writePlaceholderForMissing('https://www.redbull.com/v3/resources/startApp.js', outDir);
        expect(written).toBe(false);
    });
});

describe('ensureDir', () => {
    const tempDirs: string[] = [];

    afterEach(() => {
        for (const dir of tempDirs.splice(0)) {
            rmSync(dir, { force: true, recursive: true });
        }
    });

    it('should create nested directories', async () => {
        const outDir = mkdtempSync(path.join(tmpdir(), 'shibuk-files-'));
        tempDirs.push(outDir);

        const nestedDir = path.join(outDir, 'assets', 'images');
        await ensureDir(nestedDir);

        expect(existsSync(path.join(outDir, 'assets'))).toBe(true);
        expect(existsSync(nestedDir)).toBe(true);
        expect(lstatSync(nestedDir).isDirectory()).toBe(true);
    });

    it('should not delete conflicting files while creating directories', async () => {
        const outDir = mkdtempSync(path.join(tmpdir(), 'shibuk-files-'));
        tempDirs.push(outDir);

        const blocker = path.join(outDir, 'assets');
        await Bun.write(blocker, 'existing-file');

        await expect(ensureDir(path.join(blocker, 'images'))).rejects.toThrow();
        expect(await Bun.file(blocker).text()).toBe('existing-file');
    });
});

describe('applyCapturedEntryHtml', () => {
    const tempDirs: string[] = [];

    afterEach(() => {
        for (const dir of tempDirs.splice(0)) {
            rmSync(dir, { force: true, recursive: true });
        }
    });

    it('should replace entry html when existing includes canvas but captured does not', async () => {
        const outDir = mkdtempSync(path.join(tmpdir(), 'shibuk-files-'));
        tempDirs.push(outDir);

        const urlStr = 'https://example.com/';
        const originHost = 'example.com';
        const absPath = path.join(outDir, 'index.html');
        const existingHtml = `<html><body><div id="app"><canvas></canvas></div>${'x'.repeat(250)}</body></html>`;
        await Bun.write(absPath, existingHtml);

        const capturedHtml = '<html><body><div id="app"></div></body></html>';
        await applyCapturedEntryHtml(urlStr, capturedHtml, outDir, originHost);

        const updated = await Bun.file(absPath).text();
        expect(updated).toBe(capturedHtml);
    });

    it('should keep existing entry html when both include canvas', async () => {
        const outDir = mkdtempSync(path.join(tmpdir(), 'shibuk-files-'));
        tempDirs.push(outDir);

        const urlStr = 'https://example.com/';
        const originHost = 'example.com';
        const absPath = path.join(outDir, 'index.html');
        const existingHtml = `<html><body><div id="app"><canvas></canvas></div>${'a'.repeat(260)}</body></html>`;
        await Bun.write(absPath, existingHtml);

        const capturedHtml = `<html><body><div id="app"><canvas></canvas></div>${'b'.repeat(260)}</body></html>`;
        await applyCapturedEntryHtml(urlStr, capturedHtml, outDir, originHost);

        const updated = await Bun.file(absPath).text();
        expect(updated).toBe(existingHtml);
    });
});
